services:
  ollama:
#    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_DEBUG=1
#      - OLLAMA_NUM_PARALLEL=8
    tty: true
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
#    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    pull_policy: always
    depends_on:
      - ollama
    ports:
#      - ${OPEN_WEBUI_PORT-3000}:8080
      - 3000:8080
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
#      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  open-webui-pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    pull_policy: always
    ports:
      - 9099:9099
    volumes:
      - ./pipelines:/app/pipelines
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama:
  open-webui:
  pipelines: